#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# MUSA: data paths, label.csv, 80/20 split and cache (SCRIPT_DIR / step1_data_split)

import os
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

__all__ = [
    "SCRIPT_DIR",
    "DATA_DIR",
    "FEATURE_DIR",
    "RESULT_DIR",
    "list_sorted_files",
    "load_labels_from_csv",
    "load_file_list_npy",
    "load_saved_data_split_only",
    "step1_data_split",
]


# Path and directory configuration

_current_file_dir = os.path.dirname(os.path.abspath(__file__))
_project_root = os.path.dirname(_current_file_dir)  # MUSA project root

# Raw data directory (MUSA/data)
SCRIPT_DIR = os.path.join(_project_root, "data")

# Subdirectories
#
# Data split cache (data_split.npy / file_list.npy / labels.npy) and feature cache (ViT features)
DATA_DIR = os.path.join(_project_root, "data")
# 3D ViT feature outputs (generated by extract_roi_vit_features.py)
FEATURE_DIR = os.path.join(_project_root, "3dvit_features")
# Results (JSON summaries, etc.)
RESULT_DIR = os.path.join(_project_root, "results")

for _d in [DATA_DIR, FEATURE_DIR, RESULT_DIR]:
    os.makedirs(_d, exist_ok=True)


def _print_train_test_label_summary(train_indices, test_indices, labels):
    # Print train/test sample counts and HC/MDD (labels aligned with file_list)
    print(f"  Training set: {len(train_indices)} samples")
    print(f"  Test set: {len(test_indices)} samples")
    print(f"  Total samples: {len(labels)}")
    print(
        f"  HC (0): {np.sum(labels == 0)}, MDD (1): {np.sum(labels == 1)}"
    )


# Utility functions

def list_sorted_files(folder: str, pattern_ext: str = ".nii.gz"):
    # List files with the given extension in a directory, sorted by filename
    if not os.path.exists(folder):
        raise FileNotFoundError(f"Directory does not exist: {folder}")

    files = [
        os.path.join(folder, f)
        for f in os.listdir(folder)
        if f.endswith(pattern_ext)
    ]
    files.sort()
    return files


def load_labels_from_csv(script_dir: str):
    # Read label.csv -> {ID: label}; supports id/label column names or first two columns
    csv_file = os.path.join(script_dir, "label.csv")
    if not os.path.exists(csv_file):
        raise FileNotFoundError(f"CSV label file not found: {csv_file}")

    df = pd.read_csv(csv_file)

    df_columns_lower = [col.lower() for col in df.columns]

    if "id" not in df_columns_lower or "label" not in df_columns_lower:
        if len(df.columns) >= 2:
            df = df.rename(columns={df.columns[0]: "ID", df.columns[1]: "label"})
        else:
            raise ValueError(
                f"Invalid CSV format: ID and label columns required. Current columns: {df.columns.tolist()}"
            )
    else:
        id_col = df.columns[df_columns_lower.index("id")]
        label_col = df.columns[df_columns_lower.index("label")]
        df = df.rename(columns={id_col: "ID", label_col: "label"})

    csv_id_to_label = {}
    for _, row in df.iterrows():
        file_id = str(row["ID"])
        label = int(row["label"])
        csv_id_to_label[file_id] = label

    print(f"Loaded {len(csv_id_to_label)} labels from CSV")
    hc_count = sum(1 for v in csv_id_to_label.values() if v == 0)
    mdd_count = sum(1 for v in csv_id_to_label.values() if v == 1)
    print(f"  HC (0): {hc_count}, MDD (1): {mdd_count}")

    return csv_id_to_label


def load_file_list_npy():
    # Load file_list.npy from DATA_DIR only (does not read data_split.npy / labels.npy)
    file_list_file = os.path.join(DATA_DIR, "file_list.npy")
    if not os.path.isfile(file_list_file):
        raise FileNotFoundError(file_list_file)
    file_list = np.load(file_list_file, allow_pickle=True)
    if file_list is None or len(file_list) == 0:
        raise ValueError(file_list_file)
    return file_list


def load_saved_data_split_only(random_state: int, test_size: float):
    # Read DATA_DIR cache only; raise if files are missing or random_state/test_size mismatch
    split_file = os.path.join(DATA_DIR, "data_split.npy")
    labels_file = os.path.join(DATA_DIR, "labels.npy")
    file_list_file = os.path.join(DATA_DIR, "file_list.npy")
    for path, label in (
        (split_file, "data_split.npy"),
        (labels_file, "labels.npy"),
        (file_list_file, "file_list.npy"),
    ):
        if not os.path.isfile(path):
            raise FileNotFoundError(
                "Saved data split not found. Call step1_data_split once in Python to generate cache, e.g.:\n"
                "  from data_split_and_paths import SCRIPT_DIR, step1_data_split\n"
                "  step1_data_split(SCRIPT_DIR, random_state=42, test_size=0.2)\n"
                f"Missing: {label}\n"
                f"Expected directory: {DATA_DIR}"
            )
    split_data = np.load(split_file, allow_pickle=True).item()
    cached_rs = split_data.get("random_state")
    cached_ts = split_data.get("test_size")
    if cached_rs != random_state or cached_ts != test_size:
        raise ValueError(
            "Saved split does not match requested random_state / test_size; "
            "load_saved_data_split_only will not re-split.\n"
            f"  Cache: random_state={cached_rs}, test_size={cached_ts}\n"
            f"  Requested: random_state={random_state}, test_size={test_size}"
        )
    train_indices = split_data["train_indices"]
    test_indices = split_data["test_indices"]
    labels = np.load(labels_file, allow_pickle=True)
    file_list = np.load(file_list_file, allow_pickle=True)
    print("=" * 70)
    print("Loading saved data split (load_saved_data_split_only)")
    print("=" * 70)
    print(
        f"✓ Loaded from {DATA_DIR} (random seed: {random_state})"
    )
    _print_train_test_label_summary(train_indices, test_indices, labels)
    return train_indices, test_indices, labels, file_list


# Step 1: data split (align sMRI with CSV -> stratified split -> write to DATA_DIR)

def step1_data_split(
    script_dir: str,
    random_state: int = 42,
    test_size: float = 0.2,
    force_regen: bool = False,
):
    print("=" * 70)
    print("Step 1: Data split (data_split_and_paths)")
    print("=" * 70)

    split_file = os.path.join(DATA_DIR, "data_split.npy")
    labels_file = os.path.join(DATA_DIR, "labels.npy")
    file_list_file = os.path.join(DATA_DIR, "file_list.npy")

    # 1) If cache exists: return when params match; otherwise regenerate
    _split_paths = (split_file, labels_file, file_list_file)
    if not force_regen and all(os.path.isfile(p) for p in _split_paths):
        split_data = np.load(split_file, allow_pickle=True).item()
        labels = np.load(labels_file, allow_pickle=True)
        file_list = np.load(file_list_file, allow_pickle=True)
        if (
            split_data.get("random_state") != random_state
            or split_data.get("test_size") != test_size
        ):
            print(
                "Saved split parameters do not match; regenerating "
                f"(random_state: {split_data.get('random_state')} vs {random_state}, "
                f"test_size: {split_data.get('test_size')} vs {test_size})"
            )
        else:
            train_indices = split_data["train_indices"]
            test_indices = split_data["test_indices"]
            print(
                f"✓ Loaded saved data split (random seed: {random_state}): {DATA_DIR}"
            )
            _print_train_test_label_summary(train_indices, test_indices, labels)
            return train_indices, test_indices, labels, file_list

    # 2) Regenerate data split
    print("Regenerating data split...")

    # 2.1 Load {ID: label} from CSV
    csv_id_to_label = load_labels_from_csv(script_dir)
    if len(csv_id_to_label) == 0:
        raise ValueError(
            f"Label dictionary is empty; check: {os.path.join(script_dir, 'label.csv')}"
        )

    # 2.2 Find sMRI files under MUSA/data/sMRI
    sMRI_dir = os.path.join(script_dir, "sMRI")
    if not os.path.exists(sMRI_dir):
        raise FileNotFoundError(f"sMRI directory not found: {sMRI_dir}")

    # Prefer channel subdirectories; otherwise search sMRI root
    sMRI_channels = ["channel1", "channel2", "channel3", "GM", "WM", "CSF"]
    sMRI_files = []
    for channel in sMRI_channels:
        channel_dir = os.path.join(sMRI_dir, channel)
        if not os.path.isdir(channel_dir):
            continue
        files = list_sorted_files(channel_dir, ".nii.gz")
        if not files:
            continue
        sMRI_files = files
        print(f"  Found {len(sMRI_files)} sMRI files (from {channel} directory)")
        break

    if not sMRI_files:
        sMRI_files = list_sorted_files(sMRI_dir, ".nii.gz")
        if sMRI_files:
            print(f"  Found {len(sMRI_files)} sMRI files (directly in sMRI directory)")

    if not sMRI_files:
        raise FileNotFoundError(f"No sMRI NIfTI files found: {sMRI_dir}")

    # 2.3 Match filename stem to CSV ID exactly
    aligned_files = []
    aligned_labels = []
    for fpath in sMRI_files:
        fname = os.path.basename(fpath)
        if fname.endswith(".nii.gz"):
            stem = fname[:-7]
        elif fname.endswith(".nii"):
            stem = fname[:-4]
        else:
            stem, _ = os.path.splitext(fname)

        if stem in csv_id_to_label:
            aligned_files.append(fpath)
            aligned_labels.append(csv_id_to_label[stem])
        else:
            print(f"sMRI file has no matching ID in CSV labels: {fname} (stem={stem})")

    if not aligned_files:
        raise ValueError(
            "No sMRI files matched labels by ID. Please verify:\n"
            "1) IDs in label.csv exactly match NIfTI filenames (without extension);\n"
            "2) File naming under MUSA/data/sMRI is correct."
        )

    file_list = np.array(aligned_files)
    labels = np.array(aligned_labels, dtype=int)

    print(f"  Valid samples matched by ID: {len(file_list)}")
    print(f"  HC (0): {np.sum(labels == 0)}, MDD (1): {np.sum(labels == 1)}")

    # 2.4 Single 80/20 stratified split via StratifiedShuffleSplit
    sss = StratifiedShuffleSplit(
        n_splits=1, test_size=test_size, random_state=random_state
    )
    train_indices, test_indices = next(sss.split(file_list, labels))

    print(
        f"Training set: {len(train_indices)} samples "
        f"(HC: {np.sum(labels[train_indices] == 0)}, "
        f"MDD: {np.sum(labels[train_indices] == 1)})"
    )
    print(
        f"Test set: {len(test_indices)} samples "
        f"(HC: {np.sum(labels[test_indices] == 0)}, "
        f"MDD: {np.sum(labels[test_indices] == 1)})"
    )

    split_data = {
        "train_indices": train_indices,
        "test_indices": test_indices,
        "random_state": random_state,
        "test_size": test_size,
    }
    np.save(split_file, split_data)
    np.save(labels_file, labels)
    np.save(file_list_file, file_list)
    print(f"✓ Data split saved to {DATA_DIR}")

    print(f"✓ Data split generated successfully (random seed: {random_state})")

    return train_indices, test_indices, labels, file_list


if __name__ == "__main__":
    # Run this file directly: load cache if params match, otherwise regenerate and save
    step1_data_split(SCRIPT_DIR, random_state=42, test_size=0.2)
